### ISSUE TITLE
[Dev log] 유아현 2023-05-02 

### ISSUE THREAD

**Issue by YuAhyeon** [jumak-dev/imojumo#95]
##  💪 오늘은 어떻게 프로젝트에 기여했나요??
👉 Context API Tab 상태 생성
👉 Client 자동 배포

## 😥 오늘의 프로젝트에서 힘든 점은 무엇인가요?
> Context API를 처음 사용했다,,, 사용법이 어렵지 않았는데 어이없는 실수 때문에 시간을 많이 잡아 먹었다. 아 왜 provider 인식 못하냐고~~ 해 놓고 return을 jsx 문법 사용하고 있으면서 파일 확장자를 ts로 설정해 두었다. 지금 생각하면 많이 어이없다,,, 그래도 해결해서 다행... Context API를 통해 드릴링 한 번을 줄일 수 있었는데 지금 Tab 과 같은 곳에 Context API 사용하는 이점을 크게 느끼지 못했으나 리덕스에 비하면 사용하기에 편리하고 코드량이 절대적으로 적다는 것을 느꼈다!

> 오랜만에 다시 배포... 처음 배포 했을 때 하루를 꼬박 센 기억이 있어서 두려웠으나 역시 아현,, 해냈다 ^_^ cloudfront에서 s3 연결했는데 바로 되길래 예전에는 route53에도 s3를 연결했었는데 cloudfront를 이용하지 않을 때 route53에 연결하는 것이라고 했다.... 호오 몰랐던 사실 또 cloutfront 설정 방법을 블로깅 한다고 해 놓고 해놓지도 않고 정적 배포 - 깃허브 액션 설정만 블로깅 해 놔서 기억 더듬더듬 하는 게 참 ^^... 오늘 블로깅까지 하고 자야겠다. 그리고 젤 어려운 yml 파일 작성 3트 성공 굿굿 실수했던 부분 아래에 정리

#### 1. 폴더명 설정
```yml      
 run: |
           aws s3 sync \
            --region ap-northeast-2 \
            dist s3://imojumo \
            --delete
            working-directory: ./
```
> 여기에서 `dist s3://imojumo \` 이 부분이 문제였다. 우리 프로젝트의 경우에는 npm run build를 수행하면 `build` 폴더가 아닌 `dist` 폴더명을 가진 빌드 폴더가 생성되는데 전에는 `build s3://imojumo \` 로 설정돼 있었다.

#### 2. AWS_CLOUDFRONT_ID 미설정
> 클라우드 프론트에서는 재접속을 하는 사용자에게 빠른 UX 경험을 위해서 페이지 이지미 캐싱으로 CDN 캐시 설정을 한다고 한다! 하지만 빌드 배포 시에 이런 캐싱 정책 때문에 바로바로 업데이트가 되지 않는데 이를 위한 캐시를 날려 주는 설정을 아래와 같이 추가했는데 코드를 넣어 놓고 AWS_CLOUDFRONT_ID 를 생성하지 않고 있었다.

```yml
    - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 업로드한 s3 파일을 각 CDN 캐시 무효화하여 리프레시 하기
      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
```

## 🧐 내일을 위해 기여해야 하는 일은?
- [x] 독서토론 목록 API 요청
- [x] 찬반토론 목록 API 요청
- [x] 페이지네이션 확인하기
